config/routes.rb
Rails.application.routes.draw do
  root to:'pages#home'

  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact'
  # get 'pages/home'

  get 'restaurants', to: 'restaurants#index'
  get 'restaurants/:id', to: 'restaurants#show', as: :restaurant
  post 'restaurants', to: 'restaurants#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  #about action
  def about
  end

  #contact action
  def contact
  end

  #home action
  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  RESTAURANTS = {
      1 => { name: "Dishoom", address: "Shoreditch, London", category: "indian" },
      2 => { name: "Sushi Samba", address: "City, London", category: "japanese" }
    }

  def index
    unless params[:food_type].blank?
    @restaurants = RESTAURANTS.select do |id, rest|
      params[:food_type] == rest[:category]
    end
  else
    @restaurants = RESTAURANTS
  end
  end

  def create
    # TODO
  end

  def show
    # without active view we have to do the below:
    id = params[:id].to_i
    @restaurants = RESTAURANTS[id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thespoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

  <footer>
  Made with love by the @Le Wagon <%= Time.now.year %>
  <%= link_to 'About', about_path %>
  <%= link_to 'Contact', contact_path %>
  <%= link_to 'Restaurants', restaurants_path %>
</footer>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<form action="/restaurants" method="get">
  <input type="text" name="food_type" placeholder="What kind of food?">
  <input type="submit">
</form>

<form action="/restaurants" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="Name">
  <input type="text" name="address" placeholder="Address">
  <input type="submit">
</form>

app/views/restaurants/index.html.erb
<h1> Welcome to The Spoon </h1>

<ul>
<% @restaurants.each do |id, restaurant| %>
  <li><%= link_to restaurant[:name], restaurant_path(id)%></li>
<% end %>
</ul>

app/views/restaurants/show.html.erb
<h1><%= @restaurants[:name] %></h1>

<p><%= @restaurants[:address] %></p>